export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Features } from './Features';
export { default as About } from './About';
export { default as Services } from './Services';
export { default as Products } from './Products';
export { default as Process } from './Process';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';